import { FirstLightSystemDefinition } from './first-light.js?v=20260819-ob137';

/** ORBITBREAK's first score-attack arena, spanning several camera views. */
export const BreakerReachSystemDefinition = {
  id: 'breaker-reach',
  contentVersion: 'breaker-reach-9',
  label: "BREAKER'S REACH",
  launchBudget: 10,
  environment: {
    backgroundColor: 0x07131e,
    fogColor: 0x07131e,
    fogDensity: 0.007,
    hemisphereSkyColor: 0xd5e8f6,
    hemisphereGroundColor: 0x243848,
    keyLightColor: 0xfff3d4,
    fillLightColor: 0x7eb2d8,
    rimLightColor: 0xa6e8ff,
    toneMappingExposure: 1.24,
  },
  circuitBonusValue: 1250,
  wardenVictoryValuePerStep: 1000,
  openingBroadcast: 'WARDEN BROADCAST · TRAVEL IS FORBIDDEN · I HUNT CONNECTION',
  wardenArrivalBroadcast: 'WARDEN BROADCAST · CONNECTION IS DISORDER · I WILL SILENCE EVERY WORLD THAT ANSWERS',
  openingBody: 'Linking them lets those worlds prosper.',
  openingBriefing: [
    {
      speaker: 'THE WARDEN',
      kicker: 'SECTOR BROADCAST',
      portrait: 'warden',
      title: 'Travel is forbidden.',
      body: 'Stay on your world. I hunt anyone who flies.',
    },
    {
      speaker: 'THE RUNNER',
      kicker: 'STOLEN COURIER',
      portrait: 'runner',
      title: 'I stole the last ship.',
      body: 'I fly the Orbitbreaker to other tiny worlds. Linking them lets those worlds prosper. Occupied worlds have Warden cages. Tap the cage to break it.',
    },
  ],
  storyBoards: {
    firstAnswer: {
      skipLabel: 'Keep flying',
      continueLabel: 'Wake the next world',
      pages: [
        {
          speaker: 'EMBER',
          kicker: 'FIRST ANSWER',
          portrait: 'ember',
          title: 'Is someone there?',
          body: 'You linked us. We prosper: lights, people, trade. That is what connection does.',
        },
        {
          speaker: 'THE RUNNER',
          kicker: 'THE WORD CARRIES',
          portrait: 'runner',
          title: 'They heard us.',
          body: 'Walk, aim, land. One more neighbour and this garden is a neighbourhood. Watch them wake.',
        },
      ],
    },
    secondAnswer: {
      skipLabel: 'Keep flying',
      continueLabel: 'Wake the third',
      pages: [
        {
          speaker: 'GROVE',
          kicker: 'SECOND VOICE',
          portrait: 'grove',
          title: 'We thought we were alone.',
          body: 'Two worlds are talking. You can see the trade. Roots are breaking their grid.',
        },
        {
          speaker: 'HAVEN',
          kicker: 'THE GARDEN ANSWERS',
          portrait: 'haven',
          title: 'Keep going.',
          body: 'When three gardens talk, the silence looks smaller. The Warden called this empty. It is not.',
        },
      ],
    },
    rangeUnlock: {
      skipLabel: 'Scout further',
      continueLabel: 'Look further',
      pages: [
        {
          speaker: 'THE RUN',
          kicker: 'THE SILENCE RECEDES',
          portrait: 'orbitbreaker',
          title: 'The dark is not as wide as they said.',
          body: 'Spindle, Quarry, Mirage, Frost, Tide and Bastion were always there. The veil was a lie. Scout the wider Reach.',
        },
        {
          speaker: 'THE RUNNER',
          kicker: 'RANGE',
          portrait: 'runner',
          title: 'It was a lie.',
          body: 'Go further. Link another world. It will look easy. That is when the hunt starts.',
        },
      ],
    },
    neighbourhood: {
      skipLabel: 'Keep flying',
      continueLabel: 'Hold this feeling',
      pages: [
        {
          speaker: 'THE NETWORK',
          kicker: 'A SYSTEM',
          portrait: 'haven',
          title: 'A whole neighbourhood is talking.',
          body: 'Windows are lit. Hulls are moving. Linking worlds is what they were for.',
        },
      ],
    },
    firstTide: {
      skipLabel: 'Keep flying',
      continueLabel: 'Listen to the water',
      pages: [
        {
          speaker: 'TIDE',
          kicker: 'SALT ANSWERS',
          portrait: 'tide',
          title: 'The water refuses its ordered orbit.',
          body: 'You linked us. Jetties remember boats. We will carry word the way the tide always did.',
        },
      ],
    },
    firstFrost: {
      skipLabel: 'Keep flying',
      continueLabel: 'Keep the ice talking',
      pages: [
        {
          speaker: 'FROST',
          kicker: 'UNDER THE CRUST',
          portrait: 'frost',
          title: 'A giant ocean turns beneath the ice.',
          body: 'You linked us. The drills are quiet. Sled-skiffs wait on the rim. We were never a still world.',
        },
      ],
    },
    firstBastion: {
      skipLabel: 'Keep flying',
      continueLabel: 'Destroy if you must',
      pages: [
        {
          speaker: 'BASTION',
          kicker: 'WATCH OPENS',
          portrait: 'bastion',
          title: 'The battery stands down.',
          body: 'You opened the watch. Occupied worlds have Warden cages. Tap the cage to break it, then launch.',
        },
      ],
    },
    firstSpindle: {
      skipLabel: 'Keep flying',
      continueLabel: 'Follow the thread',
      pages: [
        {
          speaker: 'THE NETWORK',
          kicker: 'WEST LOOM',
          portrait: 'haven',
          title: 'The looms take a legal warp.',
          body: 'You linked us. Spindle kept weaving isolation cages. One live thread and the pattern remembers neighbours.',
        },
      ],
    },
    firstQuarry: {
      skipLabel: 'Keep flying',
      continueLabel: 'Take the stone home',
      pages: [
        {
          speaker: 'THE RUN',
          kicker: 'SOUTH PIT',
          portrait: 'orbitbreaker',
          title: 'The haul turns around.',
          body: 'You linked us. Quarry stopped feeding Command. The stone will build houses, not cages.',
        },
      ],
    },
    firstMirage: {
      skipLabel: 'Keep flying',
      continueLabel: 'Read the glass',
      pages: [
        {
          speaker: 'THE RUNNER',
          kicker: 'NORTH GLASS',
          portrait: 'runner',
          title: 'Command is a reflection.',
          body: 'You linked us. Mirage shows the moving crown. Two gold loops still crack it.',
        },
      ],
    },
    wardenArrival: {
      skipLabel: 'Face the hunt',
      continueLabel: 'Outrun it',
      pages: [
        {
          speaker: 'THE WARDEN',
          kicker: 'UNAUTHORISED NETWORK',
          portrait: 'warden',
          title: 'Unauthorised network detected.',
          body: 'Connection is disorder. Movement is disobedience. I hunt anyone who links a world. I will silence every world that answers.',
        },
        {
          speaker: 'THE RUNNER',
          kicker: 'THE HUNT BEGINS',
          portrait: 'runner',
          title: 'It found us.',
          body: 'It hunts the weakest linked world. Close a gold loop to push it back, or keep expanding and risk the cage.',
        },
      ],
    },
    circuitClosed: {
      skipLabel: 'Keep flying',
      continueLabel: 'Hold or expand',
      pages: [
        {
          speaker: 'THE NETWORK',
          kicker: 'LOOP CLOSED',
          portrait: 'haven',
          title: 'The signal went around.',
          body: 'This gold loop cannot be silenced at one choke. The Warden was pushed back. One shield cracked.',
        },
        {
          speaker: 'THE RUNNER',
          kicker: 'RESISTANCE',
          portrait: 'runner',
          title: 'We can defend this.',
          body: 'Gold means protected. Land on another neighbour, or close the second loop and crack the crown.',
        },
      ],
    },
    suppression: {
      skipLabel: 'Keep flying',
      continueLabel: 'Go back for them',
      pages: [
        {
          speaker: 'THE WARDEN',
          kicker: 'SIGNAL LOST',
          portrait: 'warden',
          title: 'Silence restored.',
          body: 'They took {world}. The cage is back. Land there again to wake it.',
        },
        {
          speaker: 'THE RUNNER',
          kicker: 'STILL THERE',
          portrait: 'runner',
          title: 'Land there again.',
          body: 'The route remembers. Recapture {world} before the hunt walks closer.',
        },
      ],
    },
    recapture: {
      skipLabel: 'Keep flying',
      continueLabel: 'Stay with them',
      pages: [
        {
          speaker: 'THE NETWORK',
          kicker: 'SIGNAL RESTORED',
          portrait: 'ember',
          title: "We're still here.",
          body: '{world} answers again. Lights, people, trade. The cage failed twice.',
        },
      ],
    },
    commandExposed: {
      skipLabel: 'Board Command',
      continueLabel: 'Hunt the crown',
      pages: [
        {
          speaker: 'COMMAND',
          kicker: 'CROWN CRACKED',
          portrait: 'command',
          title: 'Two loops hit the hull.',
          body: 'The shield moons are gone. The Command World is a moving tiny world now. Track it and land.',
        },
        {
          speaker: 'THE RUN',
          kicker: 'YOUR CHARGE',
          portrait: 'orbitbreaker',
          title: 'A network cannot be imprisoned.',
          body: 'Track it. Land. Walk the rim. Tap the cage. The Reach will answer together.',
        },
      ],
    },
    commandApproach: {
      skipLabel: 'Destroy the cage',
      continueLabel: 'Walk the rim',
      pages: [
        {
          speaker: 'COMMAND',
          kicker: 'CORE LATTICE',
          portrait: 'command',
          title: 'You are on the crown.',
          body: 'Occupied worlds have Warden cages. Tap the cage to break it.',
        },
      ],
    },
    reachAnswers: {
      skipLabel: 'See the route',
      continueLabel: 'Bank the route',
      pages: [
        {
          speaker: 'THE NETWORK',
          kicker: 'THE REACH ANSWERS',
          portrait: 'haven',
          title: 'You did not save them alone.',
          body: 'You reminded them they were never alone. Linked worlds answer: garden, furnaces, ice and watch, all at once.',
        },
      ],
    },
    runLost: {
      skipLabel: 'Begin again',
      continueLabel: 'Steal the ship again',
      pages: [
        {
          speaker: 'THE WARDEN',
          kicker: 'THE STILLNESS CLOSES',
          portrait: 'warden',
          title: 'You were one world too slow.',
          body: 'Isolation is safety. Connection is a fault I have closed.',
        },
        {
          speaker: 'THE RUNNER',
          kicker: 'NOT FINISHED',
          portrait: 'runner',
          title: 'Steal the ship again.',
          body: 'Haven is still a garden. Fly the Orbitbreaker. Link the worlds. Outrun the hunt.',
        },
      ],
    },
  },
  rangeUnlockLine: 'The dark is not as wide as they said.',
  furtherLandingLine: 'A whole neighbourhood is talking.',
  commandApproachLine: 'A network cannot be imprisoned.',
  camera: {
    followPlayer: true,
    viewportWorldHeight: 24,
    viewportWorldWidth: 20,
    outOfBoundsDistance: 96,
  },
  completion: {
    eyebrow: "BREAKER'S REACH LIBERATED",
    title: 'The first command signal is broken.',
    perfectTitle: 'Every signal in the Reach is free.',
    body: 'You flew the Orbitbreaker, linked the tiny worlds, and broke Command. The freed worlds are answering one another.',
    perfectBody: 'The entire Reach shines. Linked worlds keep talking.',
    endingReveal: 'You did not save them alone. You reminded them they were never alone.',
    expansionSting: 'WARDEN NODE DISCONNECTED · SECTOR WARDENS: 11',
    emblems: {
      heart: { title: 'COMMAND', subtitle: 'DEFEATED' },
      bloom: { title: 'SOLIDARITY', subtitle: 'ALL WORLDS' },
      arc: { title: 'WAYFINDER', subtitle: '3 STARDUST' },
    },
    continueToNextSystem: true,
  },
  constellation: {
    nodes: [
      { id: 'meadow', label: 'Haven', x: 36, y: 64 },
      { id: 'ember', label: 'Ember', x: 70, y: 82 },
      { id: 'grove', label: 'Grove', x: 108, y: 58 },
      { id: 'tide', label: 'Tide', x: 154, y: 46 },
      { id: 'frost', label: 'Frost', x: 70, y: 28 },
      { id: 'bastion', label: 'Bastion', x: 128, y: 20 },
      { id: 'spindle', label: 'Spindle', x: 8, y: 34 },
      { id: 'quarry', label: 'Quarry', x: 110, y: 96 },
      { id: 'mirage', label: 'Mirage', x: 182, y: 14 },
      { id: 'ledge', label: 'Ledge', x: 22, y: 48 },
      { id: 'cinder', label: 'Cinder', x: 92, y: 86 },
      { id: 'glasswing', label: 'Glasswing', x: 158, y: 28 },
      { id: 'worldheart', label: 'Command', x: 214, y: 34, isHeart: true },
    ],
    edges: [
      ['meadow', 'ember'], ['ember', 'grove'], ['grove', 'tide'],
      ['meadow', 'frost'], ['frost', 'bastion'], ['bastion', 'tide'],
      ['meadow', 'ledge'], ['ledge', 'spindle'], ['spindle', 'frost'],
      ['ember', 'cinder'], ['cinder', 'quarry'], ['quarry', 'tide'],
      ['bastion', 'glasswing'], ['glasswing', 'mirage'], ['tide', 'glasswing'],
      ['glasswing', 'worldheart'], ['mirage', 'worldheart'],
    ],
  },
  startingWorldIdentifier: 'meadow',
  openingGuideTargetIdentifier: 'ember',
  innerClusterWorldIdentifiers: ['meadow', 'ember', 'grove'],
  furtherReachWorldIdentifiers: ['tide', 'frost', 'bastion', 'spindle', 'quarry', 'mirage'],
  worldheartUnlockThreshold: 3,
  commandWorldRequiresShieldBreaks: true,
  routeSuggestions: {
    meadow: ['ember', 'frost', 'ledge'],
    ember: ['grove', 'cinder'],
    grove: ['tide', 'frost'],
    frost: ['bastion', 'ledge'],
    bastion: ['glasswing', 'tide'],
    tide: ['glasswing', 'cinder'],
    spindle: ['ledge', 'frost'],
    quarry: ['cinder', 'tide'],
    mirage: ['worldheart', 'glasswing'],
    ledge: ['spindle', 'meadow'],
    cinder: ['quarry', 'ember'],
    glasswing: ['worldheart', 'mirage'],
    seedstone: ['bastion', 'grove'],
  },
  routeGuidance: {
    grove: {
      meadow: "Walk Grove's far rim, then aim back around Ember until the path locks Haven. That gold loop protects these worlds.",
    },
    frost: {
      ember: 'Aim at Ember to close a gold loop, or go the long way through Grove. Either second loop cracks Command open.',
    },
  },
  worlds: [
    {
      ...FirstLightSystemDefinition.worlds[0],
      label: 'HAVEN', position: { x: -22, y: -8, z: 0 }, gravitationalParameter: 240,
      relayPort: { angleRadians: -0.34, halfWidthRadians: 1 },
      occupationScarAngles: [-0.34, 2.8, 1.2],
      occupationSites: [
        { longitude: -0.34, latitude: 0.16 },
        { longitude: 2.8, latitude: -0.42 },
        { longitude: 1.2, latitude: 0.92 },
      ],
      memory: 'The Runner leaves the last free garden behind.',
    },
    {
      ...FirstLightSystemDefinition.worlds[1],
      position: { x: -8, y: -13, z: 0 }, radius: 3.2, gravitationalParameter: 340,
      relayPort: { angleRadians: 2.8, halfWidthRadians: 1 },
      occupationScarAngles: [2.8, 0.57, -1.85, 1.5],
      occupationSites: [
        { longitude: 2.8, latitude: 0.14 },
        { longitude: 0.57, latitude: 0.22 },
        { longitude: -1.85, latitude: -0.48 },
        { longitude: 1.5, latitude: 0.94 },
      ],
      hostileEncounter: {
        clampOffsetsRadians: [1.5],
        cutHitRadius: 0.48,
        maxCutLength: 2.85,
      },
      memory: 'The furnaces remember who they warmed.',
    },
    {
      ...FirstLightSystemDefinition.worlds[2],
      position: { x: 6, y: -4, z: 0 }, radius: 2.5, gravitationalParameter: 240,
      relayPort: { angleRadians: -2.57, halfWidthRadians: 0.9 },
      occupationScarAngles: [-2.57, 0.62, -0.9],
      occupationSites: [
        { longitude: -2.57, latitude: 0.18 },
        { longitude: 0.62, latitude: -0.44 },
        { longitude: -0.9, latitude: 0.88 },
      ],
      hostileEncounter: {
        clampOffsetsRadians: [1.5],
        cutHitRadius: 0.48,
        maxCutLength: 2.85,
      },
      memory: 'Roots split the perfect grid from below.',
      restoration: {
        ...FirstLightSystemDefinition.worlds[2].restoration,
        atmosphereOpacity: 0.14,
        waveColor: 0xe8ffc8,
      },
    },
    {
      ...FirstLightSystemDefinition.worlds[4],
      position: { x: 24, y: 4, z: 0 }, radius: 2.8, gravitationalParameter: 260,
      relayPort: { angleRadians: 1.47, halfWidthRadians: 0.8 },
      occupationScarAngles: [1.18, 1.37, 1.56, 1.75],
      occupationSites: [
        { longitude: 1.18, latitude: 0.18 },
        { longitude: 1.37, latitude: -0.42 },
        { longitude: 1.56, latitude: 0.88 },
        { longitude: 1.75, latitude: -0.28 },
      ],
      memory: 'The water refuses its ordered orbit.',
      restoration: {
        ...FirstLightSystemDefinition.worlds[4].restoration,
        atmosphereOpacity: 0.14,
      },
    },
    {
      ...FirstLightSystemDefinition.worlds[3],
      position: { x: -8, y: 11, z: 0 }, radius: 4.2, gravitationalParameter: 320,
      slingshotValue: 1000, liberationValue: 1400,
      relayPort: { angleRadians: -1.9, halfWidthRadians: 0.85 },
      occupationScarAngles: [-2.08, -1.9, -1.72],
      occupationSites: [
        { longitude: -2.08, latitude: 0.18 },
        { longitude: -1.9, latitude: -0.42 },
        { longitude: -1.72, latitude: 0.88 },
      ],
      memory: 'A giant ocean turns beneath the ice.',
    },
    {
      id: 'bastion', label: 'BASTION', visualKey: 'vault',
      position: { x: 14, y: 18, z: 0 }, radius: 2.8, gravitationalParameter: 250,
      slingshotValue: 650, liberationValue: 1500,
      aliveColor: 0x746fa8, atmosphereColor: 0xb7b7ff, accentColor: 0xf2c1ff,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true,
      relayPort: { angleRadians: 0.28, halfWidthRadians: 0.75 },
      occupationScarAngles: [0.08, 0.28, 0.48],
      occupationSites: [
        { longitude: 0.08, latitude: 0.18 },
        { longitude: 0.28, latitude: -0.42 },
        { longitude: 0.48, latitude: 0.88 },
      ],
      disposition: 'hostile',
      hostileEncounter: {
        clampOffsetsRadians: [1.5, 2.05, 2.6],
        cutHitRadius: 0.48,
        maxCutLength: 2.85,
      },
      memory: 'The watchtowers turn their lights away from the Command World.',
      restoration: {
        durationSeconds: 2.25, waveWidth: 0.048, growthTrailWidth: 0.19,
        waveColor: 0xf1d4ff, atmosphereOpacity: 0.12, rotationSpeed: 0.0008,
        surfaceVariation: 0.055,
      },
    },
    {
      id: 'spindle', label: 'SPINDLE', visualKey: 'loom',
      position: { x: -58, y: 23, z: 0 }, radius: 2.35, gravitationalParameter: 46,
      slingshotValue: 550, liberationValue: 1200,
      aliveColor: 0x789a7c, atmosphereColor: 0xb9e2c5, accentColor: 0xcfe89a,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      relayPort: { angleRadians: -0.38, halfWidthRadians: 0.75 },
      occupationScarAngles: [2.05, 2.28, 2.51],
      occupationSites: [
        { longitude: 2.05, latitude: 0.18 },
        { longitude: 2.28, latitude: -0.42 },
        { longitude: 2.51, latitude: 0.88 },
      ],
      memory: 'The looms remember every route they were forbidden to weave.',
      restoration: {
        durationSeconds: 1.9, waveWidth: 0.055, growthTrailWidth: 0.2,
        waveColor: 0xe4f8bd, atmosphereOpacity: 0.12, rotationSpeed: 0.00065,
        surfaceVariation: 0.09,
      },
    },
    {
      id: 'quarry', label: 'QUARRY', visualKey: 'kiln',
      position: { x: 11, y: -50, z: 0 }, radius: 2.7, gravitationalParameter: 54,
      slingshotValue: 700, liberationValue: 1300,
      aliveColor: 0xb76545, atmosphereColor: 0xffad72, accentColor: 0xffcf76,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      relayPort: { angleRadians: 1.79, halfWidthRadians: 0.75 },
      occupationScarAngles: [-1.15, -0.92, -0.69],
      occupationSites: [
        { longitude: -1.15, latitude: 0.18 },
        { longitude: -0.92, latitude: -0.42 },
        { longitude: -0.69, latitude: 0.88 },
      ],
      memory: 'The pit stops sending stone to Command and starts sending it home.',
      restoration: {
        durationSeconds: 2.3, waveWidth: 0.048, growthTrailWidth: 0.18,
        waveColor: 0xffd9a0, atmosphereOpacity: 0.12, rotationSpeed: 0.00115,
        surfaceVariation: 0.05,
      },
    },
    {
      id: 'mirage', label: 'MIRAGE', visualKey: 'shard',
      position: { x: 58, y: 43, z: 0 }, radius: 3.1, gravitationalParameter: 66,
      slingshotValue: 900, liberationValue: 1600,
      aliveColor: 0x7085a8, atmosphereColor: 0xb9cdf9, accentColor: 0xd8e5ff,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      relayPort: { angleRadians: -2.5, halfWidthRadians: 0.75 },
      occupationScarAngles: [0.72, 0.94, 1.16, 1.38],
      occupationSites: [
        { longitude: 0.72, latitude: 0.18 },
        { longitude: 0.94, latitude: -0.42 },
        { longitude: 1.16, latitude: 0.88 },
        { longitude: 1.38, latitude: -0.28 },
      ],
      memory: 'The glass shows the moving crown instead of an empty sky.',
      restoration: {
        durationSeconds: 2.4, waveWidth: 0.044, growthTrailWidth: 0.2,
        waveColor: 0xe9f2ff, atmosphereOpacity: 0.12, rotationSpeed: 0.0009,
        surfaceVariation: 0.04,
      },
    },
    {
      id: 'ledge', label: 'LEDGE', visualKey: 'outpost',
      position: { x: -37, y: 8, z: 0 }, radius: 1.15, gravitationalParameter: 26,
      slingshotValue: 250, liberationValue: 300,
      aliveColor: 0x8d8f9f, atmosphereColor: 0xcdd4e6, accentColor: 0xffe2a8,
      initiallyRestored: true, countsTowardRestoration: false, biomeStyle: 2,
      memory: 'A courier shelf carved for ships that were never allowed to come.',
      restoration: {
        durationSeconds: 1.2, waveWidth: 0.06, growthTrailWidth: 0.2,
        waveColor: 0xf3ecd2, atmosphereOpacity: 0, rotationSpeed: 0.0011,
        surfaceVariation: 0.12,
      },
    },
    {
      id: 'cinder', label: 'CINDER', visualKey: 'outpost',
      position: { x: 0, y: -24, z: 0 }, radius: 1.1, gravitationalParameter: 24,
      slingshotValue: 250, liberationValue: 300,
      aliveColor: 0x9d7f72, atmosphereColor: 0xe8c9b4, accentColor: 0xffc790,
      initiallyRestored: true, countsTowardRestoration: false, biomeStyle: 2,
      memory: 'A cooled slag rock where the haul barges once caught their breath.',
      restoration: {
        durationSeconds: 1.2, waveWidth: 0.06, growthTrailWidth: 0.2,
        waveColor: 0xffe1c2, atmosphereOpacity: 0, rotationSpeed: 0.0013,
        surfaceVariation: 0.12,
      },
    },
    {
      id: 'glasswing', label: 'GLASSWING', visualKey: 'outpost',
      position: { x: 34, y: 24, z: 0 }, radius: 1.15, gravitationalParameter: 26,
      slingshotValue: 250, liberationValue: 300,
      aliveColor: 0x7f93ad, atmosphereColor: 0xc9dcf7, accentColor: 0xbde4ff,
      initiallyRestored: true, countsTowardRestoration: false, biomeStyle: 2,
      memory: 'A splinter of mirror rock that remembers every forbidden route.',
      restoration: {
        durationSeconds: 1.2, waveWidth: 0.06, growthTrailWidth: 0.2,
        waveColor: 0xe4f1ff, atmosphereOpacity: 0, rotationSpeed: 0.0009,
        surfaceVariation: 0.12,
      },
    },
  ],
  tacticalBodies: [
    {
      ...FirstLightSystemDefinition.tacticalBodies[0],
      position: { x: 2, y: 2.5, z: 0 },
    },
    {
      ...FirstLightSystemDefinition.tacticalBodies[1],
      orbit: {
        centre: { x: 24, y: 4, z: 0 }, radius: 7,
        phaseRadians: -1.05, angularSpeedRadiansPerSecond: 0.28,
      },
    },
    {
      ...FirstLightSystemDefinition.tacticalBodies[2],
      position: { x: 44.5, y: 18, z: 0 },
      orbit: {
        centre: { x: 40, y: 18, z: 0 }, radius: 4.5,
        phaseRadians: 0, angularSpeedRadiansPerSecond: 0.08,
      },
      hostileEncounter: {
        clampOffsetsRadians: [1.5, 2.05, 2.6],
        cutHitRadius: 0.5,
        maxCutLength: 2.7,
      },
    },
  ],
  stardust: [
    { id: 'breaker-arc-1', position: { x: -16, y: -1, z: 0 } },
    { id: 'breaker-arc-2', position: { x: -14, y: 4, z: 0 } },
    { id: 'breaker-arc-3', position: { x: -6, y: 10, z: 0 } },
  ],
};

