/** ORBITBREAK's second arena: a wide mining belt built around one moving hazard window. */
export const BrokenBeltSystemDefinition = {
  id: 'broken-belt',
  contentVersion: 'broken-belt-1',
  label: 'SHATTERBELT',
  launchBudget: 8,
  openingBody: 'The Stillness mines this broken belt. Take the lower convoy, or time the Sentinel and bend around Shard.',
  camera: {
    followPlayer: true,
    viewportWorldHeight: 24,
    viewportWorldWidth: 20,
    outOfBoundsDistance: 62,
  },
  environment: {
    backgroundColor: 0x090b16,
    fogColor: 0x090b16,
    fogDensity: 0.009,
    hemisphereSkyColor: 0xc7b8de,
    hemisphereGroundColor: 0x241521,
    keyLightColor: 0xffdfba,
    fillLightColor: 0x8e78b8,
    rimLightColor: 0xff9c70,
    toneMappingExposure: 1.2,
  },
  completion: {
    eyebrow: 'SHATTERBELT LIBERATED',
    title: 'The mining command goes dark.',
    perfectTitle: 'Every voice in the belt is free.',
    body: 'The broken convoy turns its lights against the Stillness.',
    perfectBody: 'Every shard and station now carries the uprising onward.',
  },
  constellation: {
    nodes: [
      { id: 'relay', label: 'Relay', x: 22, y: 72 },
      { id: 'loom', label: 'Loom', x: 58, y: 28 },
      { id: 'shard', label: 'Shard', x: 114, y: 18 },
      { id: 'drift', label: 'Drift', x: 166, y: 50 },
      { id: 'kiln', label: 'Kiln', x: 70, y: 72 },
      { id: 'vault', label: 'Vault', x: 198, y: 38 },
      { id: 'belt-heart', label: 'Belt Heart', x: 216, y: 68, isHeart: true },
    ],
    edges: [
      ['relay', 'loom'], ['relay', 'kiln'], ['loom', 'shard'],
      ['loom', 'drift'], ['kiln', 'drift'], ['drift', 'shard'],
      ['drift', 'vault'], ['shard', 'vault'], ['vault', 'belt-heart'],
    ],
  },
  startingWorldIdentifier: 'relay',
  openingGuideTargetIdentifier: 'kiln',
  innerClusterWorldIdentifiers: ['relay', 'kiln', 'loom'],
  furtherReachWorldIdentifiers: ['shard', 'drift', 'vault'],
  worldheartUnlockThreshold: 3,
  routeSuggestions: {
    relay: ['loom', 'kiln'],
    loom: ['drift', 'shard', 'kiln'],
    kiln: ['drift', 'splinter', 'loom'],
    drift: ['vault', 'shard', 'kiln'],
    shard: ['vault', 'drift', 'loom'],
    vault: ['belt-heart', 'shard', 'drift'],
    splinter: ['drift', 'vault'],
  },
  worlds: [
    {
      id: 'relay', label: 'RELAY', visualKey: 'relay',
      position: { x: -24, y: -8, z: 0 }, radius: 3.35, gravitationalParameter: 92,
      slingshotValue: 300, liberationValue: 1000,
      aliveColor: 0x658f84, atmosphereColor: 0xa7e1c7, accentColor: 0xf4dc8f,
      initiallyRestored: true, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'The last free relay had kept calling into the dark.',
      restoration: {
        durationSeconds: 2.2, waveWidth: 0.045, growthTrailWidth: 0.18,
        waveColor: 0xf6edbd, atmosphereOpacity: 0, rotationSpeed: 0.00045,
        surfaceVariation: 0.08,
      },
    },
    {
      id: 'kiln', label: 'KILN', visualKey: 'kiln',
      position: { x: -10, y: -7, z: 0 }, radius: 3, gravitationalParameter: 82,
      slingshotValue: 450, liberationValue: 1000,
      aliveColor: 0xb76545, atmosphereColor: 0xffad72, accentColor: 0xffcf76,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'The furnaces turn their heat away from the Stillness foundries.',
      restoration: {
        durationSeconds: 2.3, waveWidth: 0.048, growthTrailWidth: 0.18,
        waveColor: 0xffd9a0, atmosphereOpacity: 0, rotationSpeed: 0.00115,
        surfaceVariation: 0.05,
      },
    },
    {
      id: 'loom', label: 'LOOM', visualKey: 'loom',
      position: { x: -13, y: 8, z: 0 }, radius: 2.3, gravitationalParameter: 50,
      slingshotValue: 500, liberationValue: 1300,
      aliveColor: 0x789a7c, atmosphereColor: 0xb9e2c5, accentColor: 0xcfe89a,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'The convoy bridges remember routes the wardens erased.',
      restoration: {
        durationSeconds: 1.9, waveWidth: 0.055, growthTrailWidth: 0.2,
        waveColor: 0xe4f8bd, atmosphereOpacity: 0, rotationSpeed: 0.00065,
        surfaceVariation: 0.09,
      },
    },
    {
      id: 'shard', label: 'SHARD', visualKey: 'shard',
      position: { x: 3, y: 11.8, z: 0 }, radius: 4, gravitationalParameter: 135,
      slingshotValue: 1200, liberationValue: 1800,
      aliveColor: 0x7085a8, atmosphereColor: 0xb9cdf9, accentColor: 0xd8e5ff,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'Every broken face reflects a different way through the blockade.',
      restoration: {
        durationSeconds: 2.55, waveWidth: 0.042, growthTrailWidth: 0.2,
        waveColor: 0xe9f2ff, atmosphereOpacity: 0, rotationSpeed: 0.00095,
        surfaceVariation: 0.04,
      },
    },
    {
      id: 'drift', label: 'DRIFT', visualKey: 'drift',
      position: { x: 17, y: 6, z: 0 }, radius: 2.3, gravitationalParameter: 54,
      slingshotValue: 550, liberationValue: 1200,
      aliveColor: 0x3e7895, atmosphereColor: 0x8fdbe6, accentColor: 0xb1f0e0,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'The drifting miners light a path for the worlds behind them.',
      restoration: {
        durationSeconds: 1.95, waveWidth: 0.052, growthTrailWidth: 0.2,
        waveColor: 0xbdf6ff, atmosphereOpacity: 0, rotationSpeed: 0.00082,
        surfaceVariation: 0.06,
      },
    },
    {
      id: 'vault', label: 'VAULT', visualKey: 'vault',
      position: { x: 24, y: 9, z: 0 }, radius: 1.8, gravitationalParameter: 32,
      slingshotValue: 700, liberationValue: 1500,
      aliveColor: 0x7c6c91, atmosphereColor: 0xcbb8e1, accentColor: 0xf2d59c,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'The sealed names become the first roll call of the uprising.',
      restoration: {
        durationSeconds: 1.7, waveWidth: 0.06, growthTrailWidth: 0.22,
        waveColor: 0xf4ddbd, atmosphereOpacity: 0, rotationSpeed: 0.00055,
        surfaceVariation: 0.07,
      },
    },
  ],
  tacticalBodies: [
    {
      id: 'splinter', label: 'SPLINTER', kind: 'seedstone',
      position: { x: 2, y: -2, z: 0 }, radius: 0.68, uses: 1,
      initiallyRestored: true, countsTowardRestoration: false,
    },
    {
      id: 'sentinel', label: 'SENTINEL', kind: 'hazard', radius: 0.9,
      countsTowardRestoration: false,
      orbit: {
        centre: { x: 3, y: 11.8, z: 0 }, radius: 5,
        phaseRadians: -1.49, angularSpeedRadiansPerSecond: 0.2,
      },
    },
    {
      id: 'belt-heart', label: 'BELT HEART', kind: 'worldheart',
      position: { x: 31, y: 13, z: 0 }, radius: 0.9,
      initiallyRestored: false, countsTowardRestoration: false,
      isRouteDestination: true, routeAvailableInitially: false,
    },
  ],
  stardust: [
    { id: 'broken-belt-arc-1', position: { x: -17.087, y: -1.701, z: 0 } },
    { id: 'broken-belt-arc-2', position: { x: -15.72, y: 0.938, z: 0 } },
    { id: 'broken-belt-arc-3', position: { x: -14.333, y: 3.575, z: 0 } },
  ],
};

