
/** ORBITBREAK's chain arena: one long flight must clear two gravity wells before landing. */
export const LongNightSystemDefinition = {
  id: 'long-night',
  contentVersion: 'long-night-1',
  label: 'LONG NIGHT',
  launchBudget: 8,
  openingBody: 'The Stillness erased every road through the dark. Follow the watchfires, or cross the hidden gravity wells in one unbroken arc.',
  camera: {
    followPlayer: true,
    viewportWorldHeight: 24,
    viewportWorldWidth: 20,
    outOfBoundsDistance: 62,
  },
  environment: {
    backgroundColor: 0x02030b,
    fogColor: 0x030411,
    fogDensity: 0.014,
    hemisphereSkyColor: 0x59617f,
    hemisphereGroundColor: 0x090914,
    keyLightColor: 0xd9dbff,
    fillLightColor: 0x574c91,
    rimLightColor: 0x8a93ff,
    toneMappingExposure: 1.08,
  },
  completion: {
    eyebrow: 'LONG NIGHT LIBERATED',
    title: 'The erased roads burn again.',
    perfectTitle: 'Every watchfire carries the dawn.',
    body: 'The freed navigators reveal the final road to the Worldheart.',
    perfectBody: 'Every world and hidden arc now burns in one unbroken constellation.',
  },
  constellation: {
    nodes: [
      { id: 'vigil', label: 'Vigil', x: 22, y: 72 },
      { id: 'hollow', label: 'Hollow', x: 62, y: 24 },
      { id: 'beacon', label: 'Beacon', x: 136, y: 16 },
      { id: 'umbra', label: 'Umbra', x: 190, y: 38 },
      { id: 'pyre', label: 'Pyre', x: 70, y: 72 },
      { id: 'lumen', label: 'Lumen', x: 112, y: 48 },
      { id: 'night-heart', label: 'Night Heart', x: 216, y: 68, isHeart: true },
    ],
    edges: [
      ['vigil', 'hollow'], ['vigil', 'pyre'], ['hollow', 'umbra'],
      ['pyre', 'lumen'], ['lumen', 'umbra'], ['umbra', 'beacon'],
      ['umbra', 'night-heart'], ['beacon', 'night-heart'],
    ],
  },
  startingWorldIdentifier: 'vigil',
  openingGuideTargetIdentifier: 'pyre',
  innerClusterWorldIdentifiers: ['vigil', 'pyre', 'hollow'],
  furtherReachWorldIdentifiers: ['beacon', 'umbra', 'lumen'],
  worldheartUnlockThreshold: 3,
  routeSuggestions: {
    vigil: ['hollow', 'pyre'],
    hollow: ['umbra', 'beacon', 'lumen'],
    pyre: ['lumen', 'nightglass', 'umbra'],
    lumen: ['umbra', 'beacon', 'pyre'],
    beacon: ['night-heart', 'umbra', 'hollow', 'lumen'],
    umbra: ['night-heart', 'beacon', 'pyre', 'lumen'],
    nightglass: ['lumen', 'beacon', 'hollow'],
  },
  worlds: [
    {
      id: 'vigil', label: 'VIGIL', visualKey: 'vigil',
      position: { x: -27, y: -9, z: 0 }, radius: 3.15, gravitationalParameter: 90,
      slingshotValue: 300, liberationValue: 1000,
      aliveColor: 0x536d72, atmosphereColor: 0x9ebfc2, accentColor: 0xf4d790,
      initiallyRestored: true, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'One watchfire kept the erased routes alive in secret.',
      restoration: {
        durationSeconds: 2.25, waveWidth: 0.044, growthTrailWidth: 0.18,
        waveColor: 0xe8e5b5, atmosphereOpacity: 0, rotationSpeed: 0.00038,
        surfaceVariation: 0.08,
      },
    },
    {
      id: 'pyre', label: 'PYRE', visualKey: 'pyre',
      position: { x: -14, y: -8, z: 0 }, radius: 2.8, gravitationalParameter: 76,
      slingshotValue: 450, liberationValue: 1000,
      aliveColor: 0x9b5447, atmosphereColor: 0xffa27e, accentColor: 0xffd08b,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'The watchfire burns the Stillness charts and reveals the lower road.',
      restoration: {
        durationSeconds: 2.2, waveWidth: 0.05, growthTrailWidth: 0.18,
        waveColor: 0xffcb93, atmosphereOpacity: 0, rotationSpeed: 0.0011,
        surfaceVariation: 0.045,
      },
    },
    {
      id: 'hollow', label: 'HOLLOW', visualKey: 'hollow',
      position: { x: -16, y: 8, z: 0 }, radius: 2.5, gravitationalParameter: 60,
      slingshotValue: 700, liberationValue: 1500,
      aliveColor: 0x5c667d, atmosphereColor: 0xa8b8dc, accentColor: 0xd5ddff,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'The empty bells remember the forbidden road between two stars.',
      restoration: {
        durationSeconds: 1.95, waveWidth: 0.054, growthTrailWidth: 0.2,
        waveColor: 0xdbe3ff, atmosphereOpacity: 0, rotationSpeed: 0.00062,
        surfaceVariation: 0.07,
      },
    },
    {
      id: 'beacon', label: 'BEACON', visualKey: 'beacon',
      position: { x: 6, y: 12, z: 0 }, radius: 4.2, gravitationalParameter: 155,
      slingshotValue: 1200, liberationValue: 1900,
      aliveColor: 0x827eab, atmosphereColor: 0xd3ceff, accentColor: 0xffefb0,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'Its buried star becomes the uprising\'s final signal.',
      restoration: {
        durationSeconds: 2.8, waveWidth: 0.04, growthTrailWidth: 0.2,
        waveColor: 0xf3e8ff, atmosphereOpacity: 0, rotationSpeed: 0.00088,
        surfaceVariation: 0.035,
      },
    },
    {
      id: 'umbra', label: 'UMBRA', visualKey: 'umbra',
      position: { x: 20, y: 7, z: 0 }, radius: 3.3, gravitationalParameter: 75,
      slingshotValue: 800, liberationValue: 1500,
      aliveColor: 0x414f76, atmosphereColor: 0x929fd3, accentColor: 0xc3d2ff,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'The navigators step from shadow with every stolen route intact.',
      restoration: {
        durationSeconds: 2.05, waveWidth: 0.05, growthTrailWidth: 0.2,
        waveColor: 0xc7d4ff, atmosphereOpacity: 0, rotationSpeed: 0.00076,
        surfaceVariation: 0.05,
      },
    },
    {
      id: 'lumen', label: 'LUMEN', visualKey: 'lumen',
      position: { x: -2, y: 5, z: 0 }, radius: 2.1, gravitationalParameter: 48,
      slingshotValue: 650, liberationValue: 1100,
      aliveColor: 0x9d884c, atmosphereColor: 0xf3dda0, accentColor: 0xfff1b5,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'The smallest lamp counted every hour until the roads returned.',
      restoration: {
        durationSeconds: 1.72, waveWidth: 0.06, growthTrailWidth: 0.22,
        waveColor: 0xffedb5, atmosphereOpacity: 0, rotationSpeed: 0.00052,
        surfaceVariation: 0.065,
      },
    },
  ],
  tacticalBodies: [
    {
      id: 'nightglass', label: 'NIGHTGLASS', kind: 'seedstone',
      position: { x: -1, y: -3, z: 0 }, radius: 0.68, uses: 1,
      initiallyRestored: true, countsTowardRestoration: false,
    },
    {
      id: 'eclipse', label: 'ECLIPSE', kind: 'hazard', radius: 0.74,
      countsTowardRestoration: false,
      orbit: {
        centre: { x: 6, y: 12, z: 0 }, radius: 5.8,
        phaseRadians: 2.8, angularSpeedRadiansPerSecond: 0.22,
      },
    },
    {
      id: 'night-heart', label: 'NIGHT HEART', kind: 'worldheart',
      position: { x: 31, y: 11, z: 0 }, radius: 0.9,
      initiallyRestored: false, countsTowardRestoration: false,
      isRouteDestination: true, routeAvailableInitially: false,
    },
  ],
  stardust: [
    { id: 'long-night-arc-1', position: { x: -21.874, y: -5.249, z: 0 } },
    { id: 'long-night-arc-2', position: { x: -20.411, y: -1.83, z: 0 } },
    { id: 'long-night-arc-3', position: { x: -18.925, y: 1.557, z: 0 } },
  ],
};
