
/** The campaign finale, recombining every learned route decision around the true Worldheart. */
export const WorldheartSystemDefinition = {
  id: 'worldheart',
  contentVersion: 'worldheart-1',
  label: 'WORLDHEART',
  launchBudget: 8,
  openingBody: 'Every liberated system is behind you. Take the final road, or gather their memories and bend every lesson into one last arc.',
  camera: {
    followPlayer: true,
    viewportWorldHeight: 24,
    viewportWorldWidth: 20,
    outOfBoundsDistance: 66,
  },
  environment: {
    backgroundColor: 0x070616,
    fogColor: 0x0b0920,
    fogDensity: 0.011,
    hemisphereSkyColor: 0x8d83b8,
    hemisphereGroundColor: 0x171126,
    keyLightColor: 0xffedd0,
    fillLightColor: 0x776bb4,
    rimLightColor: 0xa9e8d0,
    toneMappingExposure: 1.18,
  },
  finale: {
    isCampaignFinale: true,
    victoryDelaySeconds: 3.4,
    pulseColor: 0xffe0a0,
    awakenedBackgroundColor: 0x19152f,
  },
  completion: {
    eyebrow: 'THE WORLDHEART IS FREE',
    title: 'The Stillness is broken.',
    perfectTitle: 'Every world answers together.',
    body: 'The liberated systems breathe as one. No road can be erased again.',
    perfectBody: 'Every route, memory and mote now shines in one living constellation.',
  },
  constellation: {
    nodes: [
      { id: 'confluence', label: 'Confluence', x: 22, y: 72 },
      { id: 'memory', label: 'Memory', x: 64, y: 24 },
      { id: 'starwell', label: 'Starwell', x: 138, y: 16 },
      { id: 'dawn', label: 'Dawn', x: 192, y: 38 },
      { id: 'kindle', label: 'Kindle', x: 70, y: 72 },
      { id: 'chorus', label: 'Chorus', x: 110, y: 48 },
      { id: 'worldheart-core', label: 'Worldheart', x: 216, y: 68, isHeart: true },
    ],
    edges: [
      ['confluence', 'memory'], ['confluence', 'kindle'], ['memory', 'chorus'],
      ['kindle', 'chorus'], ['chorus', 'dawn'], ['dawn', 'starwell'],
      ['starwell', 'worldheart-core'], ['dawn', 'worldheart-core'],
    ],
  },
  startingWorldIdentifier: 'confluence',
  openingGuideTargetIdentifier: 'kindle',
  innerClusterWorldIdentifiers: ['confluence', 'kindle', 'memory'],
  furtherReachWorldIdentifiers: ['starwell', 'dawn', 'chorus'],
  worldheartUnlockThreshold: 3,
  routeSuggestions: {
    confluence: ['memory', 'kindle'],
    memory: ['memory-moon', 'chorus', 'starwell'],
    kindle: ['chorus', 'memory-moon', 'dawn'],
    chorus: ['dawn', 'starwell', 'kindle'],
    starwell: ['worldheart-core', 'dawn', 'memory', 'chorus'],
    dawn: ['worldheart-core', 'starwell', 'kindle', 'chorus'],
    'memory-moon': ['dawn', 'starwell', 'chorus'],
  },
  worlds: [
    {
      id: 'confluence', label: 'CONFLUENCE', visualKey: 'confluence',
      position: { x: -28, y: -10, z: 0 }, radius: 3.2, gravitationalParameter: 92,
      slingshotValue: 300, liberationValue: 1000,
      aliveColor: 0x5e8178, atmosphereColor: 0xa9e8d0, accentColor: 0xffdda0,
      initiallyRestored: true, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'Every road you freed was already flowing toward this last refuge.',
      restoration: {
        durationSeconds: 2.35, waveWidth: 0.044, growthTrailWidth: 0.18,
        waveColor: 0xe9f1bd, atmosphereOpacity: 0, rotationSpeed: 0.00042,
        surfaceVariation: 0.075,
      },
    },
    {
      id: 'kindle', label: 'KINDLE', visualKey: 'kindle',
      position: { x: -15, y: -9, z: 0 }, radius: 2.9, gravitationalParameter: 78,
      slingshotValue: 500, liberationValue: 1100,
      aliveColor: 0xa55f50, atmosphereColor: 0xffad82, accentColor: 0xffe09d,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'The first spark and the last watchfire recognise one another.',
      restoration: {
        durationSeconds: 2.3, waveWidth: 0.05, growthTrailWidth: 0.18,
        waveColor: 0xffcd94, atmosphereOpacity: 0, rotationSpeed: 0.00105,
        surfaceVariation: 0.045,
      },
    },
    {
      id: 'memory', label: 'MEMORY', visualKey: 'memory',
      position: { x: -16, y: 8, z: 0 }, radius: 2.6, gravitationalParameter: 62,
      slingshotValue: 750, liberationValue: 1600,
      aliveColor: 0x668777, atmosphereColor: 0xbbe2ca, accentColor: 0xe2edc2,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'Roots, bridges, moons and bells kept the same promise in different words.',
      restoration: {
        durationSeconds: 2.05, waveWidth: 0.054, growthTrailWidth: 0.2,
        waveColor: 0xd8efcf, atmosphereOpacity: 0, rotationSpeed: 0.00064,
        surfaceVariation: 0.065,
      },
    },
    {
      id: 'starwell', label: 'STARWELL', visualKey: 'starwell',
      position: { x: 6, y: 12, z: 0 }, radius: 4.3, gravitationalParameter: 160,
      slingshotValue: 1300, liberationValue: 2000,
      aliveColor: 0x817cac, atmosphereColor: 0xd8d0ff, accentColor: 0xffe7a5,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'The gravity of every small defiance becomes a road through the dark.',
      restoration: {
        durationSeconds: 2.9, waveWidth: 0.04, growthTrailWidth: 0.2,
        waveColor: 0xf0e5ff, atmosphereOpacity: 0, rotationSpeed: 0.00086,
        surfaceVariation: 0.035,
      },
    },
    {
      id: 'dawn', label: 'DAWN', visualKey: 'dawn',
      position: { x: 22, y: 7, z: 0 }, radius: 3.2, gravitationalParameter: 78,
      slingshotValue: 850, liberationValue: 1600,
      aliveColor: 0xb18461, atmosphereColor: 0xffd7a6, accentColor: 0xfff1b3,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 2,
      memory: 'Dawn is every liberated world choosing to answer at once.',
      restoration: {
        durationSeconds: 2.18, waveWidth: 0.05, growthTrailWidth: 0.2,
        waveColor: 0xffe7b6, atmosphereOpacity: 0, rotationSpeed: 0.00078,
        surfaceVariation: 0.05,
      },
    },
    {
      id: 'chorus', label: 'CHORUS', visualKey: 'chorus',
      position: { x: -2, y: 5, z: 0 }, radius: 2.2, gravitationalParameter: 50,
      slingshotValue: 700, liberationValue: 1200,
      aliveColor: 0x7e9171, atmosphereColor: 0xcfe6ae, accentColor: 0xffedaa,
      initiallyRestored: false, usesMergedSurfaceLandmarks: true, biomeStyle: 1,
      memory: 'No world survived alone; together, they become the uprising\'s song.',
      restoration: {
        durationSeconds: 1.82, waveWidth: 0.06, growthTrailWidth: 0.22,
        waveColor: 0xe9efb5, atmosphereOpacity: 0, rotationSpeed: 0.00056,
        surfaceVariation: 0.06,
      },
    },
  ],
  tacticalBodies: [
    {
      id: 'memory-moon', label: 'MEMORY MOON', kind: 'seedstone',
      position: { x: -7.4, y: 5, z: 0 }, radius: 0.82, uses: 1,
      countsTowardRestoration: false, isRouteDestination: true,
      routeAvailableInitially: true,
      orbit: {
        centre: { x: -2, y: 5, z: 0 }, radius: 5.4,
        phaseRadians: Math.PI, angularSpeedRadiansPerSecond: 0.18,
      },
    },
    {
      id: 'last-shadow', label: 'LAST SHADOW', kind: 'hazard', radius: 0.74,
      countsTowardRestoration: false,
      orbit: {
        centre: { x: 6, y: 12, z: 0 }, radius: 5.8,
        phaseRadians: 2.8, angularSpeedRadiansPerSecond: 0.22,
      },
    },
    {
      id: 'worldheart-core', label: 'WORLDHEART', kind: 'worldheart',
      position: { x: 32, y: 11, z: 0 }, radius: 1.3,
      initiallyRestored: false, countsTowardRestoration: false,
      isRouteDestination: true, routeAvailableInitially: false,
    },
  ],
  stardust: [
    { id: 'worldheart-arc-1', position: { x: -22.747, y: -6.28, z: 0 } },
    { id: 'worldheart-arc-2', position: { x: -21.206, y: -2.898, z: 0 } },
    { id: 'worldheart-arc-3', position: { x: -19.642, y: 0.447, z: 0 } },
  ],
};
